# Generated by Django 6.0 on 2026-01-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('escolha', 'Múltipla escolha'), ('booleano', 'Sim / Não')], max_length=20)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formularios.formulario')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='formularios.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.FloatField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.pergunta')),
                ('valor_opcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formularios.opcao')),
                ('resposta_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios.respostaformulario')),
            ],
        ),
    ]
