# Generated by Django 5.2.12 on 2026-03-24 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('escolha', 'Multipla escolha'), ('escala', 'Escala de 1 a 5')], max_length=20)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formularios.formulario')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='formularios.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='egresso.egresso', verbose_name='Egresso')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularios.formulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-enviado_em'],
                'unique_together': {('formulario', 'egresso')},
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(verbose_name='Valor da Resposta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.pergunta', verbose_name='Pergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='formularios.resposta', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='egresso.egresso', verbose_name='Egresso')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='formularios.formulario', verbose_name='Questionario')),
            ],
        ),
    ]
