# Generated by Django 6.0.4 on 2026-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_rename_modelos_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formularioegresso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('escolha', 'Múltipla escolha'), ('escala', 'Escala de 1 a 5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
