# Generated by Django 5.2.12 on 2026-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('ano_conclusao', models.IntegerField(verbose_name='Ano de Conclusão')),
                ('situacao_profissional', models.CharField(choices=[('empregado', 'Empregado (CLT)'), ('autonomo', 'Autônomo / Freelancer'), ('empresario', 'Empresário'), ('desempregado', 'Desempregado'), ('estudando', 'Estudando'), ('outro', 'Outro')], default='desempregado', max_length=20, verbose_name='Situação Profissional')),
                ('empresa_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa Atual')),
                ('faixa_salarial', models.CharField(blank=True, choices=[('ate_2k', 'Até R$ 2.000'), ('2k_4k', 'R$ 2.000 – R$ 4.000'), ('4k_7k', 'R$ 4.000 – R$ 7.000'), ('7k_12k', 'R$ 7.000 – R$ 12.000'), ('acima_12k', 'Acima de R$ 12.000')], max_length=20, null=True, verbose_name='Faixa Salarial')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
