# Generated by Django 3.2.25 on 2026-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('birthDate', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(max_length=30, verbose_name='Gênero')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('number', models.CharField(max_length=11, verbose_name='Número')),
            ],
        ),
    ]
