# Generated by Django 6.0 on 2026-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresso',
            old_name='genero',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='egresso',
            name='status',
            field=models.CharField(default='Empregado', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
