# Generated by Django 5.2.6 on 2026-04-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0002_egresso_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresso',
            options={'verbose_name': 'Egresso', 'verbose_name_plural': 'Egressos'},
        ),
        migrations.AlterField(
            model_name='egresso',
            name='ano_conclusao',
            field=models.IntegerField(verbose_name='Ano de Conclusao'),
        ),
        migrations.AlterField(
            model_name='egresso',
            name='faixa_salarial',
            field=models.CharField(blank=True, choices=[('ate_2k', 'Ate R$ 2.000'), ('2k_4k', 'R$ 2.000 - R$ 4.000'), ('4k_7k', 'R$ 4.000 - R$ 7.000'), ('7k_12k', 'R$ 7.000 - R$ 12.000'), ('acima_12k', 'Acima de R$ 12.000')], max_length=20, null=True, verbose_name='Faixa Salarial'),
        ),
        migrations.AlterField(
            model_name='egresso',
            name='situacao_profissional',
            field=models.CharField(choices=[('empregado', 'Empregado (CLT)'), ('autonomo', 'Autonomo / Freelancer'), ('empresario', 'Empresario'), ('desempregado', 'Desempregado'), ('estudando', 'Estudando'), ('outro', 'Outro')], default='desempregado', max_length=20, verbose_name='Situacao Profissional'),
        ),
    ]
