# Generated by Django 5.2.6 on 2026-04-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0003_alter_egresso_options_alter_egresso_ano_conclusao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresso',
            name='faixa_salarial',
        ),
        migrations.RemoveField(
            model_name='egresso',
            name='situacao_profissional',
        ),
    ]
