# Generated by Django 5.2.6 on 2026-04-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0004_remove_egresso_faixa_salarial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresso',
            name='empresa_atual',
        ),
    ]
