# Generated by Django 5.2.6 on 2026-04-16 11:35

import django.db.models.deletion
from django.db import migrations, models


def migrar_cursos_para_relacao(apps, schema_editor):
    Curso = apps.get_model('curso', 'Curso')
    Egresso = apps.get_model('egresso', 'Egresso')

    for egresso in Egresso.objects.all().iterator():
        nome_curso = ' '.join((egresso.curso or '').split()) or 'Nao informado'
        curso = Curso.objects.filter(nome__iexact=nome_curso).first()

        if curso is None:
            curso = Curso.objects.create(nome=nome_curso)

        egresso.curso_rel_id = curso.id
        egresso.save(update_fields=['curso_rel'])


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('egresso', '0005_remove_egresso_empresa_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresso',
            name='curso_rel',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='egressos',
                to='curso.curso',
                verbose_name='Curso',
            ),
        ),
        migrations.RunPython(migrar_cursos_para_relacao, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='egresso',
            name='curso',
        ),
        migrations.RenameField(
            model_name='egresso',
            old_name='curso_rel',
            new_name='curso',
        ),
        migrations.AlterField(
            model_name='egresso',
            name='curso',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='egressos',
                to='curso.curso',
                verbose_name='Curso',
            ),
        ),
    ]
